#!/bin/sh
FREE_OLD=$(df -k /scratch --output=avail|tail -n 1)
sleep 60
id testingn00 && find /scratch/ -xdev -nouser -delete
FREE_NEW=$(df -k /scratch --output=avail|tail -n 1)
if [ $((FREE_NEW-FREE_OLD)) -gt 0 ]; then
    echo "Очистка файлов без владельцев в /scratch"
    echo "Освобождено: $(( (FREE_NEW-FREE_OLD)/1024)) мегабайт"
    echo ""
fi
