---
  - hosts: all,localhost
    gather_facts: no
    run_once: True
    tasks:
    - name: check if bringup is needed
      stat:
        path: /var/bringup_complete
      register: bringup_complete
    - name: fact set
      set_fact:
        bringup: "{{ bringup_complete.stat.exists }}"
      delegate_to: localhost
      delegate_facts: yes

  - hosts: all
    remote_user: root
    tasks:
    - include: tasks/copyansiblehosts.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/installtemperaturereport.yml
    - include: tasks/installuserregistration.yml

  - import_playbook: bringup.yml
    when: (not hostvars.localhost.bringup) and (ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10','11','12'])

# All classes, including terminal server
  - hosts: classes
    remote_user: root
    tasks:
    - include: tasks/deploy_single_signon_for_browsers.yml
    - include: tasks/updatetimezone.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/install_unattended_upgrades.yml
    - name: remove sudo
      action: apt pkg=sudo state=absent update_cache=no
    - name: update kerberos configs
      copy: src=files/common/etc/krb5.conf dest=/etc/krb5.conf owner=root group=root mode="0644"

  - hosts: a445
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a445/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

  - hosts: a439
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

  - hosts: a437
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

  - hosts: a425
    remote_user: root
    tasks:
    - include: tasks/install_faculty.yml
    - name: deploy admin access
      copy: src=files/a425/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

  - hosts: a443
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a443/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

  - hosts: a441
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

  - hosts: terminalservers
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

  - hosts: remoteteaching
    remote_user: root
    tasks:
    - name: install discord
      action: apt pkg=discord state=latest install_recommends=no update_cache=no
    - name: install zoom
      action: apt pkg=zoom state=latest install_recommends=no update_cache=no

  - hosts: a44304.dcti.sut.ru
    remote_user: root
    tasks:
    - include: tasks/install_telegram.yml
    - name: setup scanner permissions
      copy: src=files/a44304/etc/security/group.conf dest=/etc/security/group.conf owner=root group=distrib mode="0664"

  - hosts: remoteprinters
    remote_user: root
    tasks:
    - include: tasks/add_remote_printer_access.yml

  - hosts: a43707.dcti.sut.ru,a43905.dcti.sut.ru,depo07.dcti.sut.ru,depo08.dcti.sut.ru
    remote_user: root
    tasks:
    - include: tasks/install_hardwarereports.yml
