---
  - hosts: all,localhost
    gather_facts: no
    run_once: True
    tasks:
    - name: check if bringup is needed
      stat:
        path: /var/bringup_complete
      register: bringup_complete
    - name: fact set
      set_fact:
        bringup: "{{ bringup_complete.stat.exists }}"
      delegate_to: localhost
      delegate_facts: yes

  - hosts: all
    remote_user: root
    tasks:
    - include: tasks/copyansiblehosts.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/installtemperaturereport.yml
    - include: tasks/installuserregistration.yml

  - import_playbook: bringup.yml
    when: (not hostvars.localhost.bringup) and (ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10','11'])

# Labs where no remote access is used
  - hosts: noremote
    remote_user: root
    tasks:
    - include: tasks/enable_grub_password.yml
#    - include: tasks/uninstalljavatests.yml
#    - include: tasks/uninstall_mysql.yml
#    - include: tasks/uninstall_apache2_and_php5.yml
#    - name: add pam group config
#      copy: src=files/a441/etc/security/group.conf dest=/etc/security/group.conf owner=root group=distrib mode="0664"

# All classes, including terminal server
  - hosts: classes
    remote_user: root
    tasks:
    - include: tasks/deploy_single_signon_for_browsers.yml
    - include: tasks/deploy_trust_for_dcti.sut.ru.yml
    - include: tasks/install_tablet_support.yml
    - include: tasks/install_virtualbox.yml
    - include: tasks/updatetimezone.yml
    - include: tasks/installdebiankeyring.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/installcodeblocks.yml
    - name: install gnuplot
      action: apt name=gnuplot state=present install_recommends=no update_cache=no
    - name: install python3-websockets
      action: apt name=python3-websockets state=present install_recommends=no update_cache=no
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no
    - name: install assembly language IDE
      apt:
        name:
          - sasm
          - libc6-dev-i386
        state: latest
        install_recommends: no
        update_cache: no
    - name: install latest chromium
      apt:
        name:
          - chromium
          - chromium-l10n
        state: latest
        install_recommends: no
        update_cache: no
    - include: tasks/installidea.yml
    - include: tasks/install_internet.yml
    - include: tasks/install_localca.yml
    - include: tasks/install_netbeans.yml
    - include: tasks/install_pycharm.yml
    - include: tasks/install_unattended_upgrades.yml
    - include: tasks/enable_quota_applet.yml
    - name: remove sudo
      action: apt pkg=sudo state=absent update_cache=no
    - name: install video players
      apt:
        name:
          - mplayer-gui
          - vlc
        state: present
        install_recommends: no
        update_cache: no
    - name: update kerberos configs
      copy: src=files/common/etc/krb5.conf dest=/etc/krb5.conf owner=root group=root mode="0644"
    - name: install autofs-hesiod
      apt: name=autofs-hesiod state=present
    - name: update autofs config2
      lineinfile: dest=/etc/auto.master line="/afs    hesiod,hesiod:filsys" insertbefore="\+auto.master"
      register: autofschange
    - name: unlink /net/eniac.dcti.sut.ru from /afs/dcti.sut.ru
      file: dest=/afs/dcti.sut.ru state=absent follow=no
      when: autofschange.changed
    - name: restart autofs
      service: name=autofs state=restarted
      when: autofschange.changed

  - hosts: a445
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a445/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/install_vmshortcuts.yml
    - name: add pam group config
      copy: src=files/a441/etc/security/group.conf dest=/etc/security/group.conf owner=root group=distrib mode="0664"

  - hosts: a439
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/install_vmshortcuts.yml

  - hosts: a437
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/install_vmshortcuts.yml
    - include: tasks/install_quartus_15.yml

  - hosts: a425
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a425/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/install_vmshortcuts.yml
    - name: add pam group config
      copy: src=files/a441/etc/security/group.conf dest=/etc/security/group.conf owner=root group=distrib mode="0664"

  - hosts: a443
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a443/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu 9400"
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu2 9400"
    - name: install scanner driver for katusha m247
      apt: pkg=sane-katusha-m247 state=latest install_recommends=no update_cache=no
    - name: setup scanner katusha m247
      action: lineinfile dest=/etc/sane.d/dll.conf state=present line="katusham247"
    - name: setup scanner katusha m247 katusha1
      action: lineinfile dest=/etc/sane.d/katusham247.conf state=present line="ip katusha1.dcti.sut.ru M247"
    - name: setup scanner katusha m247 katusha2
      action: lineinfile dest=/etc/sane.d/katusham247.conf state=present line="ip katusha2.dcti.sut.ru M247"

  - hosts: a441
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu 9400"
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu2 9400"
    - name: install scanner driver for katusha m247
      apt: pkg=sane-katusha-m247 state=latest install_recommends=no update_cache=no
    - name: setup scanner katusha m247
      action: lineinfile dest=/etc/sane.d/dll.conf state=present line="katusham247"
    - name: setup scanner katusha m247 katusha1
      action: lineinfile dest=/etc/sane.d/katusham247.conf state=present line="ip katusha1.dcti.sut.ru M247"
    - name: setup scanner katusha m247 katusha2
      action: lineinfile dest=/etc/sane.d/katusham247.conf state=present line="ip katusha2.dcti.sut.ru M247"

  - hosts: terminalservers
    remote_user: root
    tasks:
    - name: Install software for 3d development and electronics
      apt:
        name:
          - freecad
          - kicad
          - kicad-doc-en
          - kicad-doc-ru
          - kicad-demos
          - kicad-footprints
          - kicad-symbols
          - kicad-templates
          - kicad-libraries
          - openscad
          - antimony
        state: latest
        install_recommends: no
        update_cache: no
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/deploy_terminalserver.yml

  - hosts: remoteteaching
    remote_user: root
    tasks:
    - name: install discord
      action: apt pkg=discord state=latest install_recommends=no update_cache=no
    - name: install zoom
      action: apt pkg=zoom state=latest install_recommends=no update_cache=no

  - hosts: a44304.dcti.sut.ru
    remote_user: root
    tasks:
    - name: setup scanner permissions
      copy: src=files/a44304/etc/security/group.conf dest=/etc/security/group.conf owner=root group=distrib mode="0664"

  - hosts: workstations1c
    remote_user: root
    tasks:
    - include: tasks/install_1c.yml

  - hosts: remoteprinters
    remote_user: root
    tasks:
    - include: tasks/add_remote_printer_access.yml

  - hosts: littlebig.dcti.sut.ru
    remote_user: root
    tasks:
    - include: tasks/installjavatests.yml
