---
  - hosts: all,localhost
    gather_facts: no
    run_once: True
    tasks:
    - name: check if bringup is needed
      stat:
        path: /var/bringup_complete
      register: bringup_complete
    - name: fact set
      set_fact:
        bringup: "{{ bringup_complete.stat.exists }}"
      delegate_to: localhost
      delegate_facts: yes

  - hosts: all
    remote_user: root
    tasks:
    - include: tasks/copyansiblehosts.yml
    - include: tasks/install_status_report.yml
    - include: tasks/install_temperature_report.yml
    - include: tasks/install_user_registration.yml
    - include_tasks: tasks/deploy_admin_access.yml
      loop: "{{ group_names | union([inventory_hostname,]) }}"
      loop_control:
        loop_var: outer_item

  - import_playbook: bringup.yml
    when: (not hostvars.localhost.bringup) and (ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12'])

# All classes, including terminal server
  - hosts: classes
    remote_user: root
    tasks:
    - include: tasks/deploy_single_signon_for_browsers.yml
    - include: tasks/update_timezone.yml
    - include: tasks/add_unburden-home.yml
    - include: tasks/cleanup_scratch.yml
    - include: tasks/install_unattended_upgrades.yml
    - include: tasks/enable_mail_applet.yml
    - name: install vncbroadcast to allow remote access
      apt: pkg=vncbroadcast state=latest update_cache=yes cache_valid_time=86400 install_recommends=no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in [ '11', '12']
    - name: remove sudo
      action: apt pkg=sudo state=absent update_cache=no
    - name: update kerberos configs
      copy: src=files/common/etc/krb5.conf dest=/etc/krb5.conf owner=root group=root mode="0644"

  - hosts: a425
    remote_user: root
    tasks:
    - include: tasks/install_faculty.yml

  - hosts: remoteteaching
    remote_user: root
    tasks:
    - name: install discord
      action: apt pkg=discord state=latest install_recommends=no update_cache=no
    - name: install zoom
      action: apt pkg=zoom state=latest install_recommends=no update_cache=no

  - hosts: a44304.dcti.sut.ru
    remote_user: root
    tasks:
    - include: tasks/install_telegram.yml
    - name: setup scanner permissions
      copy: src=files/a44304/etc/security/group.conf dest=/etc/security/group.conf owner=root group=distrib mode="0664"

  - hosts: remoteprinters
    remote_user: root
    tasks:
    - include: tasks/add_remote_printer_access.yml
    handlers:
    - include: handlers/restartp910nd.yml
  
  - hosts: workstations1c
    remote_user: root
    tasks:
    - include: tasks/install_1c.yml

  - hosts: a43707.dcti.sut.ru,a43905.dcti.sut.ru
    remote_user: root
    tasks:
    - include: tasks/install_hardwarereports.yml
