---
- hosts: classes, !a43706.dcti.sut.ru
  remote_user: root
  tasks:
    - name: copy sources.list to sources.list.d/old.list
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11']
      copy:
        dest: /etc/apt/sources.list.d/old.list
        remote_src: true
        src: /etc/apt/sources.list
        mode: 0644
        owner: root
        force: false
    - name: switch bullseye to bookworm
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11']
      copy:
        src: files/debian12/etc/apt/sources.list
        dest: /etc/apt/sources.list
        mode: 0644
        owner: root
    - name: Remove old repo
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'
      action: apt_repository repo='deb http://apt.dcti.sut.ru/debian/ bonch11 main' state=absent
    - name: Add new repo
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'
      action: apt_repository repo='deb http://apt.dcti.sut.ru/debian/ bonch12 main' state=present
    - name: apt-get update
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'
      apt:
        update_cache: yes
        cache_valid_time: 1
    - name: apt-get upgrade
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'
      apt:
        upgrade: safe
        force_apt_get: true
    - name: apt-get dist-upgrade
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'
      apt:
        upgrade: dist
        force_apt_get: true
    - name: remove backup old.list
      file:
        path: /etc/apt/sources.list.d/old.list
        state: absent
