   - name: install gpg
     apt: pkg=gpg state=present
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11', '12', '13']

   - name: Add key for local PIVT repo to machine
     action: apt_key url=http://apt.dcti.sut.ru/apt.gpg state=present

   - name: Add new repo
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'
     action: apt_repository repo='deb http://apt.dcti.sut.ru/debian/ bonch11 main' state=present

   - name: Add new repo
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '12'
     action: apt_repository repo='deb http://apt.dcti.sut.ru/debian/ bonch12 main' state=present

   - name: Add new repo
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '13'
     action: apt_repository repo='deb http://apt.dcti.sut.ru/debian/ bonch13 main' state=present

