    - name: deploy remote access
      apt:
        state: present
        install_recommends: no
        update_cache: no
        name:
          - websockify
          - ttyd
          - tigervnc-standalone-server
          - novnc=1:1.3.0-pivt
    - name: upload ttyd config
      copy: src=files/termserver/etc/default/ttyd dest=/etc/default/ttyd owner=root group=root mode="0644"
    - name: upload websockify service file
      copy: src=files/termserver/lib/systemd/system/websockify.service dest=/lib/systemd/system/websockify.service owner=root group=root mode="0644"
# Add deployment of noVNC files
    - name: enable and run ttyd
      systemd:
        name: ttyd
        state: started
        enabled: yes
    - name: enable and run websockify
      systemd:
        name: websockify
        state: started
        enabled: yes
    - name: Add lightdm config
      blockinfile:
        dest: /etc/lightdm/lightdm.conf
        backup: no
        insertafter: ^[VNCServer].*$
        content: |
          enabled=true
          command=Xvnc -SecurityTypes None
          port=5900
          listen-address=0.0.0.0
          width=1280
          height=1024
          depth=24
