    - name: set unrestricted for linux
      lineinfile:
        state: present
        regexp: '^CLASS="--class (.*)$'
        line: 'CLASS="--unrestricted --class \1'
        path: /etc/grub.d/10_linux
        backrefs: yes
      register: unrestricted
    - name: set unrestricted for windows
      lineinfile:
        state: present
        regexp: '^([ \t]*)CLASS="--class (.*)$'
        line: '\1CLASS="--unrestricted --class \2'
        path: /etc/grub.d/30_os-prober
        backrefs: yes
      register: unrestricted2
    - name: set password 1
      lineinfile:
        state: present
        line: 'set superusers="root"'
        path: /etc/grub.d/40_custom
      register: superuser
    - name: set password 2
      lineinfile:
        state: present
        line: >
          password_pbkdf2 root grub.pbkdf2.sha512.10000.E34442611211B5799F706F2D67805CB95
          CA2DADF179093C1BFD4C37B88726790B407538F58476509045D7230948A482742546FC959D483F2
          826C3C52EACF776A.C2E02EBE98D5B73A3422027076B9601D9EC0D1077BB81152C7DD0DF63E7BB4
          CD4A8AD639C19A270A8359A5BA68E17948969426C84941F7126EF397C5F8D5FC8B
        path: /etc/grub.d/40_custom
      register: superuserpassword
    - name: grub_update
      command: /usr/sbin/update-grub2
      when: unrestricted.changed or unrestricted2.changed or superuser.changed or superuserpassword.changed
