    - name: install openssh-server
      apt: pkg=openssh-server state=present
    - name: enable kerberos ssh
      apt:
        pkg:
          - sshpass
          - krb5-user
          - libpam-krb5
        state: present
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','10','11','12']
    - name: enable gssapi authentication 1
      lineinfile:
        state: present
        regexp: "^#?[ \t]*GSSAPIAuthentication "
        line: "GSSAPIAuthentication yes"
        path: /etc/ssh/sshd_config
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['12','11','10']
    - name: enable gssapi authentication 2
      lineinfile:
        state: present
        regexp: "^#?[ \t]*GSSAPIKeyExchange "
        line: "GSSAPIKeyExchange yes"
        path: /etc/ssh/sshd_config
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['12','11','10']


# FIXME - needs to edit /etc/ssh/sshd_config (GSSAPIAuthentication yes, GSSAPIKeyExchange yes)
