    - name: enable quota applet
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12','13']
      apt:
        pkg: quota-applet
        state: latest

    - name: Add quota-applet to autostart
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12','13']
      copy:
        src: /usr/share/applications/quota-applet.desktop
        dest: /etc/xdg/autostart/
        mode: 0755
        remote_src: yes
