    - name: install rust
      apt:
        pkg:
         - rustc
         - cargo
         - rust-gdb
         - rust-doc
        state: present
        install_recommends: no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10','11','12']

