    - name: install terminus fonts
      apt:
        pkg:
          - xfonts-terminus
          - xfonts-terminus-oblique
          - xfonts-terminus-dos
        state: present
    - name: install terminus fonts (debian 11)
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12']
      apt:
        pkg:
          - fonts-terminus
          - fonts-terminus-otb
        state: present
