    - name: install sql databases (sqlite)
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','10','11','12']
      apt:
        pkg:
         - sqlite3
         - libsqlite3-dev
         - libsqlitecpp-dev
        state: present
        install_recommends: no
    - name: install sql databases (mysql)
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','10']
      apt:
        pkg:
         - python-mysqldb
        state: present
        install_recommends: no
    - name: install sql databases (mysql)
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12']
      apt:
        pkg:
         - python3-mysqldb
        state: present
        install_recommends: no
    - name: install mysql-server
      apt:
        pkg:
         - mariadb-server
        state: present
        install_recommends: no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10','11','12']
    - name: install mysql-server
      apt:
        pkg:
         - mysql-server
        state: present
        install_recommends: no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9'] # FIXME - available in 'unstable'  - may be rebuild?
    - name: install mysql-workbench
      apt:
        pkg:
         - mysql-workbench
        state: present
        install_recommends: no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','10']
    - name: create test table in mysql
      action: mysql_db login_user=root login_password="" name=Test
