    - name: install nscd
      action: apt name=nscd state=absent update_cache=no
    - name: install unscd
      action: apt name=unscd state=present update_cache=no
    - name: update nscd config
      copy:
        src: files/common/etc/nscd.conf
        dest: /etc/nscd.conf
        owner: root
        group: root
        mode: 0644
