- name: Install octave
  ansible.builtin.apt:
    name: octave
    state: present
    install_recommends: false
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12','13']
- name: Install fonts for octave
  ansible.builtin.apt:
    name:
      - fonts-freefont-otf
      - fonts-freefont-ttf
    state: present
    install_recommends: false
- name: Install python3-sympy for symbolic maths
  ansible.builtin.apt:
    name:
      - python3-sympy
    state: present
