    - name: install JDK
      apt: pkg=openjdk-11-jdk state=present
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10','11','12']

    - name: install JDK
      apt: pkg=openjdk-8-jdk state=present
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9']
