    - name: install fixed version of linux-headers-amd64 and linux-image-amd64
      apt:
        name:
          - linux-headers-amd64=6.1.69-1~bpo11+1-pivt
          - linux-image-amd64=6.1.69-1~bpo11+1-pivt
        state: present
        force: true
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11']
    - name: set hold to linux-headers-amd64 (to prevent breaking upgrades for nvidia)
      dpkg_selections:
        name: linux-headers-amd64
        selection: hold
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11']
    - name: set hold to linux-image-amd64 (to prevent breaking upgrades for nvidia)
      dpkg_selections:
        name: linux-image-amd64
        selection: hold
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11']
    - name: remove old kernel
      apt:
        name:
          - linux-image-6.1.0-0.deb11.18-amd64
          - linux-headers-6.1.0-0.deb11.18-amd64
        state: absent
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11']
