   - name: Install vnc viewer
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10','11','12']
     action: apt name=xtightvncviewer state=present update_cache=no
