    - name: install apache2
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12','13']
      apt:
        pkg:
         - apache2
         - libapache2-mod-php
         - libapache2-mod-python
         - php-mysql
        state: present

    - name: adjust /var/www rights
      action: file mode=777 path=/var/www recurse=yes
