   - name: Install python modules
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['13','12','11']
     apt:
       name:
         - python3-requests
         - python3-psutil
         - python3-dbus
       state: present
       update_cache: no
   - name: deploy report script
     copy: src=files/common/usr/local/bin/computer_report.py dest=/usr/local/bin/computer_report.py owner=root group=root mode=755
   - name: add to periodic execution
     cron: day=* hour=* minute=*/5 month=* weekday=* job=/usr/local/bin/computer_report.py name=computerreport
