    - name: install ipython
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == ['10','11']
      apt:
        pkg:
         - ipython
         - ipython3
        state: present
        install_recommends: no
    - name: install ipython3
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == ['12']
      apt:
        pkg:
         - ipython3
        state: present
        install_recommends: no
