    - name: install golang
      apt: pkg=go state=present install_recommends=no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9', '10','11']
    - name: install golang
      apt: pkg=golang-go state=present install_recommends=no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['12']
