    - name: install script depends
      apt:
        pkg:
         - graphicsmagick-imagemagick-compat
         - x11-xserver-utils
        state: present
        install_recommends: no
        update_cache: no
    - name: install script
      copy:
        src: files/a437/etc/lightdm/display.sh
        dest: /etc/lightdm/display.sh
        owner: root
        group: root
        mode: "0755"
    - name: update configs 1
      copy:
        src: files/a437/etc/lightdm/lightdm.conf
        dest: /etc/lightdm/lightdm.conf
        mode: "0644"
    - name: update configs 2
      copy:
        src: files/a437/etc/lightdm/lightdm-gtk-greeter.conf
        dest: /etc/lightdm/lightdm-gtk-greeter.conf
        mode: "0644"
