    - name: install linux-headers from backports and linux-image
      apt:
        name:
          - linux-headers-amd64
          - linux-image-amd64
        state: latest
        default_release: bullseye-backports
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11']
