    - name: Install remmina
      apt:
        pkg:
          - remmina
          - remmina-plugin-rdp
        state: present
        install_recommends: no
    - name: Install network-manager
      apt:
        pkg:
          - network-manager-gnome
          - network-manager-l2tp-gnome
        state: present
        install_recommends: no
    - name: stop and disable xl2tpd service
      systemd:
        enabled: false
        state: stopped
        name: xl2tpd
