    - name: install ipython
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == ['11']
      apt:
        pkg:
         - ipython
        state: present
        install_recommends: no
    - name: install ipython3
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == ['11','12']
      apt:
        pkg:
         - ipython3
        state: present
        install_recommends: no
