    - name: install codeblocks
      action: apt name=codeblocks state=latest install_recommends=no
    - name: install codeblocks-contrib and dependencies
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','10']
      apt:
        name:
         - codeblocks-contrib
         - libwxbase3.0-dev
         - libwxgtk3.0-dev
    - name: install codeblocks-contrib and dependencies
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12']
      apt:
        name:
         - codeblocks-contrib
         - libwxbase3.0-dev
         - libwxgtk3.0-gtk3-dev
