    - name: install qtsdk
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12'] # FIXME - update to qt6 on debian 12
      apt:
        pkg:
         - qtcreator
         - qt5-doc
         - qt5-doc-html
         - qmlscene
         - qtbase5-dev-tools
         - qtbase5-dev
         - qtbase5-private-dev
         - qtdeclarative5-dev
         - qtscript5-dev
         - qtdeclarative5-dev-tools
         - qttools5-dev-tools
         - qttools5-dev
         - qtxmlpatterns5-dev-tools
         - cmake
         - make
         - gdb
        state: present
        install_recommends: no
