    - name: install khal/khard/vdirsyncer/todoman
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['11','12']
      apt:
        pkg:
         - khal
         - khard
         - vdirsyncer
         - todoman
         - calcurse
        state: present
    - name: install khal/khard/vdirsyncer/todoman
      apt: pkg=ncal state=present
