    - name: uninstall tomcat8
      apt:
        pkg:
         - tomcat8
         - tomcat8-admin
         - tomcat8-common
         - tomcat8-examples
         - tomcat8-user
         - tomcat8-docs
         - libtomcat8-java
        state: absent
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9']

    - name: uninstall tomcat9
      apt:
        pkg:
         - tomcat9
         - tomcat9-admin
         - tomcat9-common
         - tomcat9-examples
         - tomcat9-user
         - tomcat9-docs
         - libtomcat9-java
        state: absent
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10','11','12']

